UNO_Q_IP = "192.168.1.50"
PC_IP = "192.168.1.100"
CMD_PORT = 5005
TELEMETRY_PORT = 5006
CAMERA_STREAM_URL = "http://192.168.1.60:81/stream"
ARUCO_DICT = "DICT_4X4_50"
DOCK_MARKER_ID = 0
MARKER_SIZE_MM = 80.0
DOCK_CENTER_TOLERANCE_PX = 40
DOCK_FINAL_DISTANCE_CM = 8.0
DOCK_APPROACH_NUDGE_MS = 150
DOCK_TURN_NUDGE_MS = 120
VOSK_MODEL_PATH = "vosk-model-small-en-us-0.15"
WAKE_WORDS = ["gepard", "rover"]
VOICE_COMMANDS = {
    "patrol": "MODE_ROAM",
    "roam": "MODE_ROAM",
    "security": "MODE_SENTINEL",
    "dock": "CMD_DOCK",
    "stop": "CMD_STOP",
    "manual": "MODE_MANUAL",
}
MOTION_SENSITIVITY = 25
MOTION_MIN_AREA = 1500
SENTINEL_LOG_DIR = "sentinel_logs"
ENABLE_FACE_RECOGNITION = False
OWNER_FACE_DIR = "owner_faces"
